### ISSUE TITLE
Apply settings across dependent repos when the base repo changes

### ISSUE THREAD

**Issue by iphydf** [probot/settings#228] opened 2020-04-24 19:48 UTC
## Prerequisites:

* Is the functionality available in the GitHub UI? Not really, but neither is the rest of this plugin. It's about automation. In theory yes: I can manually walk over all my settings pages and sync settings by eye and clicking buttons.

* Is the functionality available through the GitHub API? Same as above.

## New Feature

When a repo with a settings.yml is pushed, I'd like all repos that have a settings.yml with `_extends: base-repo` to also have their settings updated.

**Comment by iphydf** [comment] 2020-04-24 19:54
Looks like it won't even sync on the next non-settings push to the repo. I guess you need to touch the settings.yml in the dependent repos somehow to force a re-evaluation of the whole config?

**Comment by iphydf** [comment] 2020-04-24 20:00
The answer is yes: if you add a comment (no semantic change) to settings.yml in the dependent repo, it reevaluates and updates the settings.

Now I'm not sure the inheritance is useful at all or whether I shouldn't just have my own validation to make sure the settings are kept in sync. Given that the settings file must be modified for the settings to propagate anyway, I might as well store all the settings in there and sync with a local script.

Is there a local script version of probot/settings? That way if I make changes to the base repo, at least I can run that locally and update all the dependent repos without pushing some arbitrary comment change to all of their settings.yml.

**Comment by travi** [comment] 2020-04-24 20:15
there are a few existing issues related to this, like https://github.com/probot/settings/issues/95. implementing the ability to propagate to those that extend is high on the priority list, but is a complex feature and required dedicated, focused time, which has been difficult to find lately.

i'm going to close this as a duplicate of #95. please know that it is known to be highly desirable, but i can't make any promises around implementation timeframe.

**Closed by travi** 2020-04-24 20:15 UTC
Labels: enhancement
