### ISSUE TITLE
Add support for 'Template repository'

### ISSUE THREAD

**Issue by SkypLabs** [probot/settings#133] opened 2019-08-17 22:42 UTC
Hi,

The [template repository](https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/) feature has been added to GitHub. To define a repository as a template, a checkbox needs to be ticked in the settings. It would be nice to be able to enable it via GitHub Settings.

Cheers.

**Comment by SkypLabs** [comment] 2019-11-25 08:09
Still relevant.

**Comment by travi** [comment] 2019-12-04 05:20
i agree that this would be valuable, but haven't had a chance to spend time on an implementation. i'd be happy to help guide you if you would be interested in attempting a PR to add this capability.

**Comment by carusogabriel** [comment] 2020-01-03 12:26
@travi Shouldn't be that difficult, right? Looks like we have the `is_template` option in GitHub's API :)

**Comment by travi** [comment] 2020-01-03 15:09
i honestly have not had time to investigate. if you've looked far enough to find that in the api docs, i'd suggest starting an initial PR with where you think it could be handled and i can help you get it to a point where it would be accepted.

**Comment by travi** [comment] 2020-02-09 21:49
@JasonEtco from what i've been able to test, this `is_template` property seems to have the same behavior as `delete_branch_on_merge` from #134

**Comment by JasonEtco** [comment] 2020-02-09 21:50
Good to know @travi, thanks - it's likely the same authentication code that doesn't properly check for Apps vs. Users. I'll let the team know 👍

**Comment by travi** [comment] 2020-02-10 04:36
sorry, i was wrong on this one @JasonEtco. i was misunderstanding how octokit applies the preview headers, so i assumed it was already being applied. i believe this will work once #199 is merged

**Closed** 2020-02-10 16:24 UTC

**Comment by travi** [comment] 2020-02-10 16:36
i've confirmed that this does work now
